### ISSUE TITLE
Get / Replace Documentation / Query

### ISSUE THREAD

**Issue by paulswithers** [stefanopog/node-red-contrib-dominodb#1]
I was trying the Replace Docs/Items node. I was trying to change a field value to one that includes a space, e.g. myFieldName=me and you. I found I had to set it to myFieldName="me and you".

Initially I tried myFieldName='me and you'. Looking at the underlying database, I then found the field was set to 'me.

I tried getting the documents, to replace it. But the Get Documents node had trouble if the field value starts with a single quote. The DQL documentation talks about escaping a single quote in the middle of a string as e.g. 'O''Malley'. If it starts with a single quote, it has problems. I tried 'me, '''me and ''me. This may be a deeper issue with DQL rather than these nodes though.

**Comment by stefanopog** [comment]
I had a similar issue Paul. 
What I do in the code (in case the string is provided in the node configuration panel) is to match the value part using this regular expression:
`const betweenQuotes = /"([^"\\]*(\\.[^"\\]*)*)"/;`
So, if you are using single quote, that is not gonna work.

If you use the input array `msg.DDB_itemValues`, i **do NOT** parse it at all so I delegate it directly to DQL. 

So my suggestion to verify the underlying behavior of DQL is to try the  `msg.DDB_itemValues` input array. In case you see differences, then I guess I have to modify the regex i mentioned above.

Pls let me know the results of your test and I will act accordingly.
Thanks so much

**Comment by stefanopog** [comment]
I just did some further test, Paul.
If you use `myFieldName='me'` then the value is set to `'me'` including the single quote. This is INCONSISTENT with what I wrote in the [official Programming Guide](https://stefanopog.github.io/node-red-contrib-dominodb-docs/docs/fullDoc-DocumentMgrNode/) so I think i need to change the regex

**Comment by paulswithers** [comment]
I tested from Node directly. There seems to be a problem in DQL itself with starting with a single quote. A single quote in the middle or end works fine. https://stackoverflow.com/questions/54217219/dql-query-format-when-field-starts-with-single-quote.

For consistency with the core DQL, it would be better if myFieldName="me and you" threw an error but myFieldName='me and you' worked.

**Comment by dcacy** [comment]
I talked with HCL and this is a defect. Thanks for identifying it!

**Comment by stefanopog** [comment]
I fixed the defect with **V0.9.8** which is available now.
