### ISSUE TITLE
dominodb config node keeps forgetting source-db settings

### ISSUE THREAD

**Issue by elem089** [stefanopog/node-red-contrib-dominodb#4]
Hi,
I'm having a repeating problem with node-red-contrib-domninodb V 1.0.1:
I configured dominodb config node to pull data from my Domino-Server V 10.0.1 (CentOS). 
The database I'm querying is not secured, so I access it as "anonymous". Thus the "secure" checkbox in the config node editor is unchecked.
The "DDB GetDocuments" node is working fine, right after editing the config node.
In the flow data file I can see that the configuration is properly stored in the json tree.
After starting a new node-red instance on my local Windows machine the getDocument node is throwing an error "TypeError: Cannot read property 'D10_isSecure' of undefined".
Editing the config node I see that fields are empty although at same time the flow file contains all needed information.
After re-configuring the node and deploying the flow everything works as expected.
This can be reproduced for any instance of config node.
---
Environment info:
Node-RED V 0.19.5
Node.js V 10.14.1

Greetings,
Lothar

**Comment by stefanopog** [comment]
Thank you for your report.
May I ask you pls the following?

- could you pls join the full console dump of the error ? Please enable the DEBUG flag before starting NodeRED in order to be sure to get the maximum level of information

- i am not sure i understand what you write "_Editing the config node I see that fields are empty although at same time the flow file contains all needed information_".  When you install node red on a new machine, you need to create a new configuration (even if it has the same information as another node red instance)

thank you
/Stefano

**Comment by elem089** [comment]
Love to help. But honestly, I'm quite new to node-red, so have to ask a few dumb questions:
>> enable DEBUG flag:
are you referring to Node-RED's own config.json? It contains a "debug" element which already was set to "enabled", but starting node-RED I get messages that debug is disabled for all DDB nodes. So I assume that's not the place to look for...

>> 2nd bullet:
If I shut down my node-RED instance then look into the flow json file (below my project folder, then <flow-name>.json) I see that all settings in regards to my server and database are there. But then after I start node-RED, then editing the config node all server and database related fields are empty. So somehow the config node seems to fail reading its config values from the json file.
So I'm NOT referring to a new installation of Node-RED but an existing one.
All the best
-Lothar

EDIT: made a screenshot from the config node right after Node-RED is started. You see in the info part of the config that all data is there as stored in the .json file. But the fields on the left hand side are empty. As soon as I filled them with the relevant values and deploy the changes my flow starts working again.

![Node-RED_DDB_Database_node](https://user-images.githubusercontent.com/43233590/55347251-9f999600-54b4-11e9-8c14-c4174365f233.png)

**Comment by stefanopog** [comment]
Hello

- as to the environment variable i was referring to, pls check this : https://stefanopog.github.io/node-red-contrib-dominodb-docs/docs/fullDoc-TechnicalDetails/

- i think you also know this site https://stefanopog.github.io/node-red-contrib-dominodb-docs/docs/fullDoc-Intro/ which contains the full documentation of the nodes.

- In general, the overall documentation, including examples and setup, are documented here: https://stefanopog.github.io/node-red-contrib-dominodb-docs/

- i am NOT using the "project feature" of Nodered, so i may miss some details of what you explain in the second bullet.

- the picture you include is weird. Normally you should at least see the "Carpool-DB" string displayed on the left "AppName" textbook. The Info tab displays the details of what is shown on the left "Edit Database node" panel. Once again, I have never used the "Project feature" in NodeRed and this may be the source of the issues you are experimenting. 

- one question. When you started using your new NodeRED instance on Windows, did you re-create the Database node? How did you transition from one NodeRED instance to the other one ? 

thanks

**Comment by elem089** [comment]
Stefano,
Thanks for your answer. I'll be away from office for a couple of days. I'm considering doing a complete new setup afterwards.
I'll be back then.
Regards
-Lothar

⁣BlueMail for Android herunterladen ​

**Comment by stefanopog** [comment]
ok.
Pls contact me back when you are available
best regards
/Stefano

**Comment by elem089** [comment]
Hi,
did a complete new installation of node.js 10.15.3 and node-red 0.20.3 inside a VM. Then installed domino-db package, which caused a few more problems (which meanwhile I could solve myself, never mind...).
This time I have NOT created a project, that'll be next on my list.
Once I finally got node-red + domino-db package v 1.0.1 up and running I could build a very simple flow using getDocuments. Restartet node-red several times, ontime even the entire VM: problem appears to be solved, config-node data now appears to be stable.
As I wrote above: next I'll create a project then will see whether this siomple node is still working.

Final question: you recommended a debug option to be set someplace, and meanwhile I also found this being mentioned in documentation: 
"Detailed logging
When setting the d10Debug environment variable to true, a verbose logging is shown in the terminal console."
Could you briefly explain, what and where that is? Thanks

**Comment by stefanopog** [comment]
Hello,
i am glad you addressed this in your new installation.
As to the debug flag, this needs to be set OUTSIDE Node-Red. It is simply an Environment variable that needs to be set according to the Operating System you are using. I assume you are using a Linux, so the command is likely `export d10Debug=true` before running node-red. You can sert it globally.... but I suggest that you activate it *when you need*.
Was my explanation clear ? 

One other point. have you seen this page https://icstechsales.github.io/think2019lab-domino-integration/docs/info-intro/ for installing the domino-db package ? 

/Stefano

**Comment by elem089** [comment]
>>  Was my explanation clear ?
I'll see what I can make out of it :D
As I wrote earlier, I'm pretty new to node.js and node-red. Been developing
Notes and Domino for 25 years, mainly Xpages and Java over the last 10
years.
My company held a 2-day event here in Munich / Germany this week, and I had
a session comparing the various target clients available today for a Domino
developer. Node-Red is great to use for visualizing / presenting stuff
where showing 100 lines of node.js code is just boring. That's why I got
into node-red, and that's why I created projects so that I can
differentiate between session stuff and my own experiments...

Node-Red is running on my local machine (Windows 10)  which is fine for my
purposes. Only the server I'm querying is a CentOS machine.
So I assume that I have to look for the Windows equivalent inside the
documentation you linked earllier this week.
Once again: many thanks for your patience with a complete noob in that field

Am Do., 4. Apr. 2019 um 16:00 Uhr schrieb Stefano Pogliani <
notifications@github.com>:

**Comment by elem089** [comment]
just for info: just realized that this is a REAL system wide env variable -
I've been looking all the time for some entry in a json file... oh dear, so
much to learn 😉
So for now debugging seems to be enabled for the ddb nodes

Am Do., 4. Apr. 2019 um 17:11 Uhr schrieb Lothar Mueller <lm4989@gmail.com>:

**Comment by stefanopog** [comment]
no **noob** on this discussion. All your questions are sound and pertinent. I hope my answers are also at a level you would expect.

**Comment by elem089** [comment]
Final (from my side) update on this issue: just enabled projects for my test setup, then result: all settings are remembered.
Conclusion for me is that I must have made some kind of mistake when setting up my fist node-red instance (where I observed that flaw)
Thanks for helping. If you wish you may close this issue.
